
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/codetrek/haystack/internal/core/vectorindex"


)

var tests = []testing.InternalTest{

	{"TestWithM", _test.TestWithM},

	{"TestWithMBoundary", _test.TestWithMBoundary},

	{"TestWithEfConstruction", _test.TestWithEfConstruction},

	{"TestWithEfConstructionDefault", _test.TestWithEfConstructionDefault},

	{"TestWithEfSearch", _test.TestWithEfSearch},

	{"TestWithEfSearchDefault", _test.TestWithEfSearchDefault},

	{"TestMultipleOptions", _test.TestMultipleOptions},

	{"TestInsertBatchMemStore", _test.TestInsertBatchMemStore},

	{"TestInsertBatchEmpty", _test.TestInsertBatchEmpty},

	{"TestInsertBatchPebbleStore", _test.TestInsertBatchPebbleStore},

	{"TestInsertBatchSingle", _test.TestInsertBatchSingle},

	{"TestMemNodeStoreSetNorm", _test.TestMemNodeStoreSetNorm},

	{"TestMemNodeStoreGetNormNotFound", _test.TestMemNodeStoreGetNormNotFound},

	{"TestMemNodeStoreGetVectorRef", _test.TestMemNodeStoreGetVectorRef},

	{"TestMemNodeStoreGetVectorRefNotFound", _test.TestMemNodeStoreGetVectorRefNotFound},

	{"TestPebbleBatchDepth", _test.TestPebbleBatchDepth},

	{"TestPebbleDiscardBatchNoActive", _test.TestPebbleDiscardBatchNoActive},

	{"TestPebbleCommitBatchNoActive", _test.TestPebbleCommitBatchNoActive},

	{"TestPebbleBatchWritesVisible", _test.TestPebbleBatchWritesVisible},

	{"TestPebbleBatchNestedCommit", _test.TestPebbleBatchNestedCommit},

	{"TestPebbleDiscardBatchDiscardsWrites", _test.TestPebbleDiscardBatchDiscardsWrites},

	{"TestPebbleSetNormAndGetNorm", _test.TestPebbleSetNormAndGetNorm},

	{"TestPebbleSetNormInBatch", _test.TestPebbleSetNormInBatch},

	{"TestPebbleGetNormNotFound", _test.TestPebbleGetNormNotFound},

	{"TestPebbleGetVectorRef", _test.TestPebbleGetVectorRef},

	{"TestPebbleGetVectorRefNotFound", _test.TestPebbleGetVectorRefNotFound},

	{"TestPebbleCachePutEviction", _test.TestPebbleCachePutEviction},

	{"TestPebbleCachePutUpdate", _test.TestPebbleCachePutUpdate},

	{"TestPebbleSetEntryPointInBatch", _test.TestPebbleSetEntryPointInBatch},

	{"TestPebbleNeighborsPrefix", _test.TestPebbleNeighborsPrefix},

	{"TestLoadVectors", _test.TestLoadVectors},

	{"TestLoadVectorsFileNotFound", _test.TestLoadVectorsFileNotFound},

	{"TestLoadQueries", _test.TestLoadQueries},

	{"TestLoadQueriesFileNotFound", _test.TestLoadQueriesFileNotFound},

	{"TestLoadGroundTruth", _test.TestLoadGroundTruth},

	{"TestLoadGroundTruthFileNotFound", _test.TestLoadGroundTruthFileNotFound},

	{"TestLoadGroundTruthInvalidHeader", _test.TestLoadGroundTruthInvalidHeader},

	{"TestLoadVectorsInvalidHeader", _test.TestLoadVectorsInvalidHeader},

	{"TestLoadVectorsTruncatedData", _test.TestLoadVectorsTruncatedData},

	{"TestInsertBatchWithCustomOptions", _test.TestInsertBatchWithCustomOptions},

	{"TestPebblePutNodeStoresNorm", _test.TestPebblePutNodeStoresNorm},

	{"TestEncodeDecodeFloat32Roundtrip", _test.TestEncodeDecodeFloat32Roundtrip},

	{"TestEncodeDecodeFloat32sRoundtrip", _test.TestEncodeDecodeFloat32sRoundtrip},

	{"TestEncodeDecodeUint64sRoundtrip", _test.TestEncodeDecodeUint64sRoundtrip},

	{"TestEncodeDecodeUint64Roundtrip", _test.TestEncodeDecodeUint64Roundtrip},

	{"TestPebbleBatchDeleteNode", _test.TestPebbleBatchDeleteNode},

	{"TestHNSWWithPebbleStoreInsertAndSearch", _test.TestHNSWWithPebbleStoreInsertAndSearch},

	{"TestPebbleSetNeighborsInBatch", _test.TestPebbleSetNeighborsInBatch},

	{"TestPebbleSetNodeMappingInBatch", _test.TestPebbleSetNodeMappingInBatch},

	{"TestPebbleDeleteNodeMappingInBatch", _test.TestPebbleDeleteNodeMappingInBatch},

	{"TestPebbleNextNodeIdInBatch", _test.TestPebbleNextNodeIdInBatch},

	{"TestPebbleCommitBatchNoSync", _test.TestPebbleCommitBatchNoSync},

	{"TestPutNodeBatchGetCountError", _test.TestPutNodeBatchGetCountError},

	{"TestPutNodeCommitErrorOnReadOnlyDB", _test.TestPutNodeCommitErrorOnReadOnlyDB},

	{"TestDeleteNodeReaderError", _test.TestDeleteNodeReaderError},

	{"TestDeleteNodeCommitErrorOnReadOnlyDB", _test.TestDeleteNodeCommitErrorOnReadOnlyDB},

	{"TestSetNeighborsErrorOnReadOnlyDB", _test.TestSetNeighborsErrorOnReadOnlyDB},

	{"TestSetNormErrorOnReadOnlyDB", _test.TestSetNormErrorOnReadOnlyDB},

	{"TestSetNodeMappingCommitErrorOnReadOnlyDB", _test.TestSetNodeMappingCommitErrorOnReadOnlyDB},

	{"TestDeleteNodeMappingReaderError", _test.TestDeleteNodeMappingReaderError},

	{"TestDeleteNodeMappingCommitErrorOnReadOnlyDB", _test.TestDeleteNodeMappingCommitErrorOnReadOnlyDB},

	{"TestRandomLevelDistribution", _test.TestRandomLevelDistribution},

	{"TestRandomLevelZeroGuard", _test.TestRandomLevelZeroGuard},

	{"TestNodeDistanceGetVectorRefError", _test.TestNodeDistanceGetVectorRefError},

	{"TestNodeDistanceSuccess", _test.TestNodeDistanceSuccess},

	{"TestPutNodeClosedDB", _test.TestPutNodeClosedDB},

	{"TestDeleteNodeClosedDB", _test.TestDeleteNodeClosedDB},

	{"TestSetNeighborsClosedDB", _test.TestSetNeighborsClosedDB},

	{"TestSetNodeMappingClosedDB", _test.TestSetNodeMappingClosedDB},

	{"TestDeleteNodeMappingClosedDB", _test.TestDeleteNodeMappingClosedDB},

	{"TestSetNormClosedDB", _test.TestSetNormClosedDB},

	{"TestNextNodeIdBatchReaderError", _test.TestNextNodeIdBatchReaderError},

	{"TestNextNodeIdCommitErrorOnReadOnlyDB", _test.TestNextNodeIdCommitErrorOnReadOnlyDB},

	{"TestSetEntryPointErrorOnReadOnlyDB", _test.TestSetEntryPointErrorOnReadOnlyDB},

	{"TestGetVectorReadError", _test.TestGetVectorReadError},

	{"TestGetVectorRefReadError", _test.TestGetVectorRefReadError},

	{"TestGetNeighborsReadError", _test.TestGetNeighborsReadError},

	{"TestGetEntryPointReadError", _test.TestGetEntryPointReadError},

	{"TestGetNodeLevelReadError", _test.TestGetNodeLevelReadError},

	{"TestGetNodeIdReadError", _test.TestGetNodeIdReadError},

	{"TestGetNormReadError", _test.TestGetNormReadError},

	{"TestPutNodeBatchPath", _test.TestPutNodeBatchPath},

	{"TestDeleteNodeBatchPath", _test.TestDeleteNodeBatchPath},

	{"TestDeleteNodeNoDocMappingBatchPath", _test.TestDeleteNodeNoDocMappingBatchPath},

	{"TestDeleteNodeNoDocMappingNonBatch", _test.TestDeleteNodeNoDocMappingNonBatch},

	{"TestSetNodeMappingBatchPath", _test.TestSetNodeMappingBatchPath},

	{"TestDeleteNodeMappingBatchPath", _test.TestDeleteNodeMappingBatchPath},

	{"TestSetNeighborsBatchPath", _test.TestSetNeighborsBatchPath},

	{"TestSetNormBatchPath", _test.TestSetNormBatchPath},

	{"TestSetEntryPointBatchPath", _test.TestSetEntryPointBatchPath},

	{"TestNextNodeIdBatchPath", _test.TestNextNodeIdBatchPath},

	{"TestRandomLevelDifferentM", _test.TestRandomLevelDifferentM},

	{"TestNodeDistanceNonExistentPebble", _test.TestNodeDistanceNonExistentPebble},

	{"TestInsertNextNodeIdError", _test.TestInsertNextNodeIdError},

	{"TestInsertPutNodeError", _test.TestInsertPutNodeError},

	{"TestInsertSetNodeMappingError", _test.TestInsertSetNodeMappingError},

	{"TestInsertSetNeighborsError", _test.TestInsertSetNeighborsError},

	{"TestInsertStaleEntryPointRecovers", _test.TestInsertStaleEntryPointRecovers},

	{"TestInsertStaleEntryPointSetEntryPointError", _test.TestInsertStaleEntryPointSetEntryPointError},

	{"TestInsertFirstNodeSetEntryPointError", _test.TestInsertFirstNodeSetEntryPointError},

	{"TestSearchGetEntryPointError", _test.TestSearchGetEntryPointError},

	{"TestSearchStaleEntryPoint", _test.TestSearchStaleEntryPoint},

	{"TestDeleteGetNodeIdError", _test.TestDeleteGetNodeIdError},

	{"TestDeleteGetNodeLevelError", _test.TestDeleteGetNodeLevelError},

	{"TestDeleteGetNeighborsError", _test.TestDeleteGetNeighborsError},

	{"TestDeleteDeleteNodeError", _test.TestDeleteDeleteNodeError},

	{"TestDeleteDeleteNodeMappingError", _test.TestDeleteDeleteNodeMappingError},

	{"TestDeleteSetNeighborsError", _test.TestDeleteSetNeighborsError},

	{"TestNodeDistanceWithNormFallback", _test.TestNodeDistanceWithNormFallback},

	{"TestInsertWithCosineDistanceMultiNode", _test.TestInsertWithCosineDistanceMultiNode},

	{"TestInsertBatchPropagatesError", _test.TestInsertBatchPropagatesError},

	{"TestDeleteNonExistentDoc", _test.TestDeleteNonExistentDoc},

	{"TestInsertAfterDeleteAll", _test.TestInsertAfterDeleteAll},

	{"TestConcurrentInsertAndSearch", _test.TestConcurrentInsertAndSearch},

	{"TestConcurrentSearchOnly", _test.TestConcurrentSearchOnly},

	{"TestConcurrentInsertDeleteSearch", _test.TestConcurrentInsertDeleteSearch},

	{"TestRandomLevel", _test.TestRandomLevel},

	{"TestNodeDistance_NonExistentNode", _test.TestNodeDistance_NonExistentNode},

	{"TestNodeDistanceWithNorm_NonExistentNode", _test.TestNodeDistanceWithNorm_NonExistentNode},

	{"TestNodeDistance_ValidNode", _test.TestNodeDistance_ValidNode},

	{"TestIntegrationResultConsistency", _test.TestIntegrationResultConsistency},

	{"TestIntegrationRestartPersistence", _test.TestIntegrationRestartPersistence},

	{"TestIntegrationDeleteRestart", _test.TestIntegrationDeleteRestart},

	{"TestIntegrationCRUD", _test.TestIntegrationCRUD},

	{"TestCosineDistance", _test.TestCosineDistance},

	{"TestCosineDistanceWithNormsEquivalence", _test.TestCosineDistanceWithNormsEquivalence},

	{"TestEuclideanDistance", _test.TestEuclideanDistance},

	{"TestDotProductDistance", _test.TestDotProductDistance},

	{"TestMemStoreBasicOperations", _test.TestMemStoreBasicOperations},

	{"TestMemStoreNeighbors", _test.TestMemStoreNeighbors},

	{"TestMemStoreEntryPoint", _test.TestMemStoreEntryPoint},

	{"TestMemStoreMapping", _test.TestMemStoreMapping},

	{"TestMemStoreDeleteNode", _test.TestMemStoreDeleteNode},

	{"TestHNSWEmptyIndex", _test.TestHNSWEmptyIndex},

	{"TestHNSWSingleVector", _test.TestHNSWSingleVector},

	{"TestHNSWRecallSmall", _test.TestHNSWRecallSmall},

	{"TestHNSWRecallLarger", _test.TestHNSWRecallLarger},

	{"TestHNSWNeighborLimits", _test.TestHNSWNeighborLimits},

	{"TestHNSWEntryPointUpdate", _test.TestHNSWEntryPointUpdate},

	{"TestHNSWDelete", _test.TestHNSWDelete},

	{"TestHNSWWithEuclideanDistance", _test.TestHNSWWithEuclideanDistance},

	{"TestHNSWWithDotProductDistance", _test.TestHNSWWithDotProductDistance},

	{"TestHNSWDeleteEntryPoint", _test.TestHNSWDeleteEntryPoint},

	{"TestHNSWDeleteAllVectors", _test.TestHNSWDeleteAllVectors},

	{"TestHNSWSearchKGreaterThanN", _test.TestHNSWSearchKGreaterThanN},

	{"TestHNSWInsertUpsert", _test.TestHNSWInsertUpsert},

	{"TestHNSWInsertUpsertMultiple", _test.TestHNSWInsertUpsertMultiple},

	{"TestExportMemStoreToMmap", _test.TestExportMemStoreToMmap},

	{"TestMetaHeaderSize", _test.TestMetaHeaderSize},

	{"TestMetaHeaderWriteRead", _test.TestMetaHeaderWriteRead},

	{"TestMetaHeaderAtomicWrite", _test.TestMetaHeaderAtomicWrite},

	{"TestWriteMetaHeaderBadDir", _test.TestWriteMetaHeaderBadDir},

	{"TestWriteMetaHeaderVersionDefault", _test.TestWriteMetaHeaderVersionDefault},

	{"TestWriteMetaHeaderRenameFailure", _test.TestWriteMetaHeaderRenameFailure},

	{"TestWriteDataFileHeaderBadPath", _test.TestWriteDataFileHeaderBadPath},

	{"TestWriteDataFileHeaderReadOnly", _test.TestWriteDataFileHeaderReadOnly},

	{"TestReadMetaHeaderMissing", _test.TestReadMetaHeaderMissing},

	{"TestReadMetaHeaderTruncated", _test.TestReadMetaHeaderTruncated},

	{"TestReadMetaHeaderBadMagic", _test.TestReadMetaHeaderBadMagic},

	{"TestMmapStoreIntegration", _test.TestMmapStoreIntegration},

	{"TestMmapStoreGetVector", _test.TestMmapStoreGetVector},

	{"TestMmapStoreGetVectorOutOfRange", _test.TestMmapStoreGetVectorOutOfRange},

	{"TestMmapStoreGetNeighborsL0", _test.TestMmapStoreGetNeighborsL0},

	{"TestMmapStoreGetNeighborsUpper", _test.TestMmapStoreGetNeighborsUpper},

	{"TestMmapStoreGetNormAndLevel", _test.TestMmapStoreGetNormAndLevel},

	{"TestMmapStoreGetNodeLevelDeleted", _test.TestMmapStoreGetNodeLevelDeleted},

	{"TestMmapStoreGetEntryPoint", _test.TestMmapStoreGetEntryPoint},

	{"TestMmapStoreGetNodeId", _test.TestMmapStoreGetNodeId},

	{"TestMmapStoreReadUpperSlotOutOfRange", _test.TestMmapStoreReadUpperSlotOutOfRange},

	{"TestMmapStoreGetNeighborsL0OutOfRange", _test.TestMmapStoreGetNeighborsL0OutOfRange},

	{"TestMmapStoreGetNeighborsUpperOutOfRange", _test.TestMmapStoreGetNeighborsUpperOutOfRange},

	{"TestMmapStoreGetNeighborsUpperSlotZero", _test.TestMmapStoreGetNeighborsUpperSlotZero},

	{"TestMmapStoreGetNeighborsUpperBadLayer", _test.TestMmapStoreGetNeighborsUpperBadLayer},

	{"TestMmapStoreGetNeighborsUpperSlotOutOfRange", _test.TestMmapStoreGetNeighborsUpperSlotOutOfRange},

	{"TestMmapStoreGetNormOutOfRange", _test.TestMmapStoreGetNormOutOfRange},

	{"TestMmapStoreGetNodeLevelOutOfRange", _test.TestMmapStoreGetNodeLevelOutOfRange},

	{"TestMmapStoreOpenClose", _test.TestMmapStoreOpenClose},

	{"TestMmapStoreOpenMismatch", _test.TestMmapStoreOpenMismatch},

	{"TestMmapStoreInvalidOpts", _test.TestMmapStoreInvalidOpts},

	{"TestMmapStoreInitBadDir", _test.TestMmapStoreInitBadDir},

	{"TestMmapStoreInitSmallCap", _test.TestMmapStoreInitSmallCap},

	{"TestMmapAllocFree", _test.TestMmapAllocFree},

	{"TestMmapAllocZeroLength", _test.TestMmapAllocZeroLength},

	{"TestMmapFreeEmpty", _test.TestMmapFreeEmpty},

	{"TestPebbleDeleteNode_WithBatch", _test.TestPebbleDeleteNode_WithBatch},

	{"TestPebbleDeleteNode_WithoutBatch", _test.TestPebbleDeleteNode_WithoutBatch},

	{"TestPebbleDeleteNode_NonExistent", _test.TestPebbleDeleteNode_NonExistent},

	{"TestPebblePutNode_WithBatch", _test.TestPebblePutNode_WithBatch},

	{"TestPebblePutNode_WithoutBatch", _test.TestPebblePutNode_WithoutBatch},

	{"TestPebbleSetNodeMapping_WithBatch", _test.TestPebbleSetNodeMapping_WithBatch},

	{"TestPebbleDeleteNodeMapping_WithBatch", _test.TestPebbleDeleteNodeMapping_WithBatch},

	{"TestPebbleDeleteNodeMapping_NonExistent", _test.TestPebbleDeleteNodeMapping_NonExistent},

	{"TestPebbleSetNeighbors_WithBatch", _test.TestPebbleSetNeighbors_WithBatch},

	{"TestPebbleSetNorm_WithBatch", _test.TestPebbleSetNorm_WithBatch},

	{"TestPebbleReadOnly_PutNode", _test.TestPebbleReadOnly_PutNode},

	{"TestPebbleReadOnly_DeleteNode", _test.TestPebbleReadOnly_DeleteNode},

	{"TestPebbleReadOnly_SetNodeMapping", _test.TestPebbleReadOnly_SetNodeMapping},

	{"TestPebbleReadOnly_DeleteNodeMapping", _test.TestPebbleReadOnly_DeleteNodeMapping},

	{"TestPebbleReadOnly_SetNeighbors", _test.TestPebbleReadOnly_SetNeighbors},

	{"TestPebbleReadOnly_SetNorm", _test.TestPebbleReadOnly_SetNorm},

	{"TestPebbleReadOnly_SetEntryPoint", _test.TestPebbleReadOnly_SetEntryPoint},

	{"TestPebbleReadOnly_NextNodeId", _test.TestPebbleReadOnly_NextNodeId},

	{"TestPutAndGetVector", _test.TestPutAndGetVector},

	{"TestPutAndGetNodeLevel", _test.TestPutAndGetNodeLevel},

	{"TestDeleteNode", _test.TestDeleteNode},

	{"TestNeighborsMultipleLayers", _test.TestNeighborsMultipleLayers},

	{"TestEntryPoint", _test.TestEntryPoint},

	{"TestNodeMapping", _test.TestNodeMapping},

	{"TestNextNodeId", _test.TestNextNodeId},

	{"TestRestartPersistence", _test.TestRestartPersistence},

	{"TestGetNonExistentNode", _test.TestGetNonExistentNode},

	{"TestDeleteNonExistentNode", _test.TestDeleteNonExistentNode},

	{"TestTableIsolation", _test.TestTableIsolation},

	{"TestEmptyNeighbors", _test.TestEmptyNeighbors},

	{"TestCloseDoesNotCloseDB", _test.TestCloseDoesNotCloseDB},

	{"TestHNSWUpsertEntryPoint", _test.TestHNSWUpsertEntryPoint},

	{"TestHNSWUpsertWithPebble", _test.TestHNSWUpsertWithPebble},

	{"TestHNSWInsertBatchDuplicateDocId", _test.TestHNSWInsertBatchDuplicateDocId},

	{"TestHNSWInsertBatchPartialFailure", _test.TestHNSWInsertBatchPartialFailure},

	{"TestHNSWUpsertPersistRestart", _test.TestHNSWUpsertPersistRestart},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/codetrek/haystack/internal/core/vectorindex"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

