project = "haystack"
module_prefix = "github.com/codetrek/haystack/"

[exclude]
packages = [
  "haystack/scripts/",
  "haystack/cmd",
]
files = [
  "internal/testutil/",
  "indexer/testing.go",
  "main.go",
]

[html]
path = ".haystack/test_coverage.html"
