# This is an example of the configuration file
# You can copy this file to config.local.yaml and modify it to your own
# configuration for local development
# The application will automatically load the configuration from config.local.yaml
# if it exists.
# The application will try to load configuration files in the following order:
#  - $CWD/config.local.yaml
#  - $CWD/config.yaml
#  - $HOME/.haystack/config.yaml
#
# Copy the file to one of the above place.

global:
  data_path: # the path to store the database files, default is $HOME/.haystack/index

client:
  # client mode specific configuration
  default_workspace: # the default workspace to search, default is empty, e.g.: D:\Edge\src
  default_limit:
    max_results: 500 # the default max results to return, default is 500
    max_results_per_file: 50 # the default max results per file to return, default is 50

server:
  max_file_size: 2097152 # the maximum file size to index, default is 2MB
  index_workers: 4 # the number of workers to index files, default is 4
  cache_size: 16 # the size of the cache to use, default is 16MB
  filters:
    exclude:
      use_git_ignore: false
      customized: ["node_modules/", "dist/", "build/", "vendor/", "out/", "obj/", "log/", "logs/", ".*", "*.log", "*.log.*", "*log.txt"]
    include:  [ # ["**/*"] to include all files
      "*.cc", "*.c", "*.hpp", "*.cpp", "*.h", "*.md", "*.js", "*.ts", "*.txt", "*.mm", "*.java","*.cs", "*.py",
      "*.kt", "*.go", "*.rb", "*.php", "*.html", "*.css", "*.yaml", "*.yml", "*.toml", "*.xml", "*.sql", "*.sh",
      "Makefile", "*.bat", "*.ps1", "*.sln", "*.json", "*.vcxproj", "*.vcproj", "*.vcxproj.filters" ]
  search:
    max_wildcard_length: 24 # the maximum length of "*" will be matched in query, default is 24
    max_keyword_distance: 32 # the maximum char distance between keywords in query, default is 32
    limit:
      max_results: 5000 # the maximum number of results to return, default is 5000
      max_results_per_file: 500 # the maximum number of results per file to return, default is 500
