# This is an example of the configuration file
# You can copy this file to config.local.yaml and modify it to your own
# configuration for local development
# The application will automatically load the configuration from config.local.yaml
# if it exists.
# The application will try to load configuration files in the following order:
#  - $CWD/config.local.yaml
#  - $CWD/config.yaml
#  - $HOME/.search-indexer/config.yaml
#
# Copy the file to one of the above place.

global:
  home_path: # the path to store the database files, default is $HOME/.search-indexer/index

client:
  # client mode specific configuration

server:
  max_file_size: 2097152 # the maximum file size to index, default is 2MB
  index_workers: 4 # the number of workers to index files, default is 4
  filters:
    exclude:
      use_git_ignore: false
      customized: ["node_modules/", "dist/", "build/", "out/", "obj/", "log/", "logs/", ".*", "*.log", "*.log.*", "*log.txt"]
    include:  ["*.cc", "*.c", "*.hpp", "*.cpp", "*.h", "*.md", "*.js", "*.ts", "*.txt", "*.mm", "*.java", "*.cs", "*.py",
              "*.kt", "*.go", "*.rb", "*.php", "*.html", "*.css", "*.yaml", "*.yml", "*.toml", "*.xml", "*.sql", "*.sh",
              "Makefile", "*.bat", "*.ps1", "*.sln", "*.json", "*.vcxproj", "*.vcproj", "*.vcxproj.filters"]
