name: Release Haystack

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        working-directory: ./src
        run: go test ./...

      - name: Run build.go
        working-directory: ./src
        run: go run build.go

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
